import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen overflow-hidden">
        <div className="flex gap-0 h-full">
          <Navbar />
          <div className="flex flex-col w-full h-full">
            <main className="flex-grow bg-gray-100 h-full overflow-y-auto">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}